import { number } from "prop-types";

export const InputTypes = {
  AUTOCOMPLETE: 'Autocomplete',
  NUMBER: 'number',
  TEXT: 'text',
  DATE: 'date'
}

export default [
  {
    id: "headers",
    title: 'CAPTURA DE DATOS',
    pdfTitle: '',
    fields: [
      {
        id: "1",
        name: "rx",
        pdfName: 'rx',
        label: "RX",
        pdfLabel: 'RX',
        width: '200px',
        pdfWidth: '400px',
        pdfHeight: '30px',
      },
      {
        id: "2",
        name: "fecha",
        pdfName: "fecha",
        label: "FECHA",
        pdfLabel: "FECHA",
        width: '200px',
        pdfWidth: '400px',
        pdfHeight: '30px',
        type: InputTypes.DATE
      },
      {
        id: "3",
        name: "cliente",
        pdfName: "cliente",
        label: "CLIENTE",
        pdfLabel: "CLIENTE",
        width: '380px',
        pdfWidth: '400px',
        pdfHeight: '30px',
      },
    ]
  },
  {
    title: 'GRADUACIÓN',
    pdfTitle: 'GRADUACIÓN',
    fields: [
      {
        id: "4",
        name: "od_esfera",
        pdfName: "od_esfera",
        label: "OD ESFERA",
        pdfLabel: "OD ESFERA",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "5",
        name: "od_cilindro",
        pdfName: "od_cilindro",
        label: "OD CILINDRO",
        pdfLabel: "OD CILINDRO",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "6",
        name: "od_eje",
        pdfName: "od_eje",
        label: "OD EJE",
        pdfLabel: "OD EJE",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "7",
        name: "od_adicion",
        pdfName: "od_adicion",
        label: "OD ADICIÓN",
        pdfLabel: "OD ADICIÓN",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "8",
        name: "od_dip",
        pdfName: "od_dip",
        label: "OD DIP",
        pdfLabel: "OD DIP",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "9",
        name: "od_altura",
        pdfName: "od_altura",
        label: "OD ALTURA",
        pdfLabel: "OD ALTURA",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "10",
        name: "oi_esfera",
        pdfName: "oi_esfera",
        label: "OI ESFERA",
        pdfLabel: "OI ESFERA",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "11",
        name: "oi_cilindro",
        pdfName: "oi_cilindro",
        label: "OI CILINDRO",
        pdfLabel: "OI CILINDRO",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "12",
        name: "oi_eje",
        pdfName: "oi_eje",
        label: "OI EJE",
        pdfLabel: "OI EJE",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "13",
        name: "oi_adicion",
        pdfName: "oi_adicion",
        label: "OI ADICIÓN",
        pdfLabel: "OI ADICIÓN",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "14",
        name: "oi_dip",
        pdfName: "oi_dip",
        label: "OI DIP",
        pdfLabel: "OI DIP",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
      {
        id: "15",
        name: "oi_altura",
        pdfName: "oi_altura",
        label: "OI ALTURA",
        pdfLabel: "OI ALTURA",
        width: '125px',
        pdfWidth: '125px',
        pdfHeight: '50px',
        type: InputTypes.NUMBER,
      },
    ]
  },
  {
    fields: [
      {
        id: "16",
        name: "diseno",
        pdfName: "diseno",
        label: "DISEÑO",
        pdfLabel: "DISEÑO",
        width: "395px",
        pdfWidth: "395px",
        pdfHeight: '50px',
        type: InputTypes.AUTOCOMPLETE,
        options: [
          "diseno 1",
          "diseno 2",
          "diseno 3",
          "diseno 4",
          "diseno 5",
        ]
      },
      {
        id: "17",
        name: "material",
        pdfName: "material",
        label: "MATERIAL",
        pdfLabel: "MATERIAL",
        width: "395px",
        pdfWidth: "395px",
        pdfHeight: '50px',
        type: InputTypes.AUTOCOMPLETE,
        options: [
          "material 1",
          "material 2",
          "material 3",
          "material 4",
          "material 5",
        ]
      },
      {
        id: "18",
        name: "tipo_ar",
        pdfName: "tipo_ar",
        label: "TIPO AR",
        pdfLabel: "TIPO AR",
        width: "395px",
        pdfWidth: "395px",
        pdfHeight: '50px',
        type: InputTypes.AUTOCOMPLETE,
        options: [
          "tipo_ar 1",
          "tipo_ar 2",
          "tipo_ar 3",
          "tipo_ar 4",
          "tipo_ar 5",
        ]
      },
      {
        id: "19",
        name: "tallado",
        pdfName: "tallado",
        label: "TALLADO",
        pdfLabel: "TALLADO",
        width: "395px",
        pdfWidth: "395px",
        pdfHeight: '50px',
        type: InputTypes.AUTOCOMPLETE,
        options: [
          "tallado 1",
          "tallado 2",
          "tallado 3",
          "tallado 4",
          "tallado 5",
        ]
      },
    ]
  },
  {
    title: 'SERVICIOS',
    pdfTitle: 'SERVICIOS',
    fields: [
      {
        id: "27",
        name: "servicios",
        label: "SERVICIOS",
        width: "800px",
        pdfWidth: '800px',
        pdfHeight: '50px',
        pdfClass: "noBorderLines"
      }
    ]
  },
  {
    title: 'ARMAZON',
    pdfTitle: 'ARMAZÓN',
    fields: [
      {
        id: "21",
        name: "tipo_de_armazon",
        label: "TIPO DE ARMAZÓN",
        width: "157px",
        pdfWidth: '150px',
        pdfHeight: '50px',
        type: InputTypes.AUTOCOMPLETE,
        options: [
          "tipo_de_armazon 1",
          "tipo_de_armazon 2",
          "tipo_de_armazon 3",
          "tipo_de_armazon 4",
          "tipo_de_armazon 5",
        ]
      },
      {
        id: "22",
        name: "horizontal_a",
        label: "HORIZONTAL 'A'",
        width: "150px",
        pdfWidth: '150px',
        pdfHeight: '50px',
      },
      {
        id: "23",
        name: "vertical_b",
        label: "VERTICAL 'B'",
        width: "150px",
        pdfWidth: '150px',
        pdfHeight: '50px',
      },
      {
        id: "24",
        name: "diagonal_ed",
        label: "DIAGONAL 'ED'",
        width: "150px",
        pdfWidth: '150px',
        pdfHeight: '50px',
      },
      {
        id: "25",
        name: "puente",
        label: "PUENTE",
        width: "157px",
        pdfWidth: '150px',
        pdfHeight: '50px',
      },
    ]
  },
  {
    title: 'OBSERVACIONES',
    pdfTitle: 'OBSERVACIONES',
    fields: [
      {
        id: "21",
        name: "observaciones",
        label: "OBSERVACIONES",
        width: "800px",
        pdfWidth: '800px',
        pdfHeight: '50px',
        pdfClass: "noBorderLines"
      },
    ]
  },
]